importScripts("contracts/job-urls.js", "contracts/job-analyses.js", "contracts/messages.js", "bridge-config.js");
try {
  importScripts("local-config.js");
} catch {
  // Generated by the local installer.
}

const bridgeConfig = globalThis.jobSearchBridgeConfig;
const messages = globalThis.jobSearchContracts.messages;
const submissionsEndpoint = `${bridgeConfig.bridgeOrigin}/cv-fit-submissions`;
const REQUEST_TIMEOUT_MS = 10_000;
let analysisSync = null;

const syncJobAnalyses = () => {
  if (analysisSync) return analysisSync;
  analysisSync = (async () => {
    if (!bridgeConfig.bridgeToken) throw new Error("Local bridge is not configured");
    const { response, body } = await requestBridgeJson(`${bridgeConfig.bridgeOrigin}/analyses`, { method: "GET" });
    if (!response.ok || !body?.ok || !Array.isArray(body.analyses)) throw new Error("Analysis records unavailable");
    const contract = globalThis.jobSearchContracts.jobAnalyses;
    const values = {};
    for (const record of body.analyses) {
      if (!contract.isRecord(record)) throw new Error("Invalid analysis record");
      values[contract.keyFor(record.jobUrl)] = record;
    }
    const prior = await chrome.storage.local.get(Object.keys(values));
    const changed = Object.fromEntries(Object.entries(values).filter(([key, record]) =>
      JSON.stringify(prior[key]) !== JSON.stringify(record)));
    if (Object.keys(changed).length) await chrome.storage.local.set(changed);
    return { ok: true };
  })().finally(() => { analysisSync = null; });
  return analysisSync;
};

const requestBridgeJson = async (endpoint, { method, body: requestBody }) => {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);
  try {
    const response = await fetch(endpoint, {
      cache: "no-store",
      method,
      signal: controller.signal,
      headers: {
        "Content-Type": "application/json",
        "X-JSC-Token": bridgeConfig.bridgeToken,
      },
      ...(method === "POST" ? { body: JSON.stringify(requestBody) } : {}),
    });
    let parseError = null;
    const body = await response.json().catch((error) => {
      parseError = error;
      return null;
    });
    return { response, body, parseError };
  } finally {
    clearTimeout(timer);
  }
};

const requestCvFitSubmission = async (message) => {
  const isStart = message.type === messages.submitCvFitTask;
  if (!isStart && !message.submissionId) {
    return { ok: false, error: "Submission ID is missing" };
  }
  const endpoint = isStart
    ? submissionsEndpoint
    : `${submissionsEndpoint}/${encodeURIComponent(message.submissionId)}`;
  try {
    const { response, body: parsedBody } = await requestBridgeJson(endpoint, {
      method: isStart ? "POST" : "GET",
      body: { jobUrl: message.jobUrl },
    });
    const body = parsedBody || {};
    return response.ok && body.ok
      ? { ok: true, ...(body.submission ? { submission: body.submission } : {}) }
      : { ok: false, error: body.error || `Request failed with status ${response.status}` };
  } catch (error) {
    return {
      ok: false,
      error: error.name === "AbortError"
        ? "The local bridge did not respond within 10 seconds"
        : error.message,
    };
  }
};

const handleCvFitMessage = (message, _sender, sendResponse) => {
  if (
    ![messages.submitCvFitTask, messages.getCvFitTaskStatus].includes(
      message?.type,
    )
  ) {
    return false;
  }
  if (!bridgeConfig.bridgeToken) {
    sendResponse({
      ok: false,
      error: "Bridge token is not configured in extension/local-config.js",
    });
    return false;
  }
  requestCvFitSubmission(message).then(sendResponse, (error) => {
    sendResponse({ ok: false, error: error.message });
  });
  return true;
};

// Restrict the new checking boundary independently of full CV analysis.
const BLOCKER_ACTIONS = new Map([
  ["status", ["GET", "/status"]],
  ["models", ["GET", "/models"]],
  ["settings", ["POST", "/settings"]],
  ["sign-in", ["POST", "/sign-in"]],
  ["cancel-sign-in", ["POST", "/cancel-sign-in"]],
  ["account", ["POST", "/account"]],
  ["sign-out", ["POST", "/sign-out"]],
  ["clear-cache", ["POST", "/clear-cache"]],
  ["check", ["POST", "/checks"]],
  ["poll", ["GET", "/checks/"]],
]);
const isIndeedSender = (sender) => {
  try {
    const url = new URL(sender.url);
    return (
      url.protocol === "https:" && globalThis.jobSearchContracts.jobUrls.isIndeedHost(url.hostname)
    );
  } catch {
    return false;
  }
};
const handleBlockerMessage = (message, sender, sendResponse) => {
  if (message?.type !== messages.blockerRequest) return false;
  const action = BLOCKER_ACTIONS.get(message.action);
  const isSettings = sender.url === chrome.runtime.getURL("options.html");
  if (
    !action ||
    (!isSettings &&
      (!isIndeedSender(sender) || !["status", "check", "poll"].includes(message.action)))
  ) {
    sendResponse({ ok: false, error: "Blocker request is not allowed" });
    return false;
  }
  if (!bridgeConfig.bridgeToken || !bridgeConfig.bridgeOrigin) {
    sendResponse({
      ok: false,
      error: "Install the local bridge to enable blocker checks.",
    });
    return false;
  }
  if (message.action === "poll" && !/^[a-f0-9-]{36}$/.test(message.id || "")) {
    sendResponse({ ok: false, error: "Invalid check ID" });
    return false;
  }
  const [method, path] = action;
  requestBridgeJson(
    `${bridgeConfig.bridgeOrigin}/blockers${path}${message.action === "poll" ? message.id : ""}`,
    { method, body: message.body || {} },
  )
    .then(({ body, parseError }) => {
      if (parseError) throw parseError;
      // Only the extension settings page may receive sign-in URLs or account state.
      if (!isSettings && body.connectionStatus) {
        body.connectionStatus = { planUsageEnabled: body.connectionStatus.planUsageEnabled };
        if (body.profile) body.profile = { hash: body.profile.hash };
      }
      sendResponse(body);
    })
    .catch((error) =>
      sendResponse({
        ok: false,
        error:
          error.name === "AbortError"
            ? "Local checker did not respond. Try again."
            : "Local checker unavailable. Check that the bridge is running.",
      }),
    );
  return true;
};
chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if ([messages.syncJobAnalyses, messages.openJobAnalysis].includes(message?.type)) {
    let allowed = false;
    try {
      const url = new URL(sender.url);
      const hosts = globalThis.jobSearchContracts.jobUrls;
      allowed = url.protocol === "https:" && (hosts.isIndeedHost(url.hostname) || hosts.isLinkedInHost(url.hostname));
    } catch { /* Reject unknown senders. */ }
    if (!allowed) { sendResponse({ ok: false, error: "Analysis request is not allowed" }); return false; }
    const action = message.type === messages.syncJobAnalyses ? syncJobAnalyses()
      : requestBridgeJson(`${bridgeConfig.bridgeOrigin}/analyses/open`, {
        method: "POST", body: { jobUrl: message.jobUrl },
      }).then(({ response, body }) => {
        if (!response.ok || !body?.ok) throw new Error(body?.error || "Couldn’t open the analysis");
        return { ok: true };
      });
    action.then(sendResponse, (error) => sendResponse({ ok: false, error: error.message }));
    return true;
  }
  if (message?.type === messages.openBlockerSettings && isIndeedSender(sender)) {
    chrome.runtime.openOptionsPage();
    sendResponse({ ok: true });
    return false;
  }
  return (
    handleCvFitMessage(message, sender, sendResponse) ||
    handleBlockerMessage(message, sender, sendResponse)
  );
});
chrome.action?.onClicked.addListener(() => chrome.runtime.openOptionsPage());
chrome.alarms?.create("sync-job-analyses", { periodInMinutes: 0.5 });
chrome.alarms?.onAlarm.addListener((alarm) => {
  if (alarm.name === "sync-job-analyses") void syncJobAnalyses().catch(() => {});
});
